package com.test;

class Customer {
	public String name;
	public long	balance;
}

public class ExceptionTest {

	public static void main(String[] args) {
		System.out.println("예외상황을 발생시켜요!");
		
		
		Customer a = null;
//		a.name = "홍길동";
		try {
		int result = 10/0;		//문법적인 오류는 없음
								//하지만 Runtime에 이상한 상황(Exception)이 발생
		} catch(NullPointerException e) {
			System.out.println("널포인터 익셉션 !");
			//원래는 예외상황 처리코드가 나와야 함
		} catch(Exception e) {	
			System.out.println("수학연산 잘못됐어요 !");
		}finally {
			//얘는 무조건 수행됨(예외가 있거나 없거나 상관없이 수행)
		}
		
		System.out.println("여기는 출력되나요 !");
	}
}
